### ISSUE TITLE
[Babun terminal] 'quasar dev' can't find the 'npm' command where run from Babun

### ISSUE THREAD

**Issue by mlenormand** [rstoenescu/quasar-cli#2]
Hi,

First, congratulations for all the work done in Quasar these last weeks ! Happy to see the community growing day after day.

Just switched to [Babun ](http://babun.github.io/)(a Windows terminal that uses Cygwin) and I can't run `quasar dev` from Babun.
When running `quasar dev` in my project folder, I have the following error :

```
'npm' is not recognized as an internal or external command,
operable program or batch file.
```
My PATH env var is OK and I can run the `npm `command without problem : 

```
{ my-app } develop » npm                          /cygdrive/l/disque/workspace/my-app
Usage: npm <command>

where <command> is one of:
    access, adduser, bin, bugs, c, cache, completion, config,
    ddp, dedupe, deprecate, dist-tag, docs, edit, explore, get,
    help, help-search, i, init, install, install-test, it, link,
    list, ln, logout, ls, outdated, owner, pack, ping, prefix,
    prune, publish, rb, rebuild, repo, restart, root, run,
    run-script, s, se, search, set, shrinkwrap, star, stars,
    start, stop, t, tag, team, test, tst, un, uninstall,
    unpublish, unstar, up, update, v, version, view, whoami

npm <cmd> -h     quick help on <cmd>
npm -l           display full usage info
npm help <term>  search for help on <term>
npm help npm     involved overview

Specify configs in the ini-formatted file:
    C:\Users\mika\.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@3.10.3 L:\disque\outils\nodejs\node_modules\npm
```
My PATH variable is exported in the .babunrc file : 

```
...

# NodeJS
export NODEJS_HOME=/cygdrive/l/disque/outils/nodejs

# NPM
export NPM_HOME=/cygdrive/l/disque/outils/npm

# Path
export PATH=${NODEJS_HOME}:${NPM_HOME}:${PATH}
```

 Child processes launched with the spawn function in node normally inherit from the parent env vars, right ? I can't understand why this child process doesn't know the npm command.

**Comment by rstoenescu** [comment]
Haven't used Babun, but until I figure this out, simply run `npm run dev`.
When on Windows Quasar CLI tries to proxy all spawned commands through `cmd.exe`. Babun might not handle your paths correctly when running through `cmd.exe`. Probably got to find a way if CLI is running under Babun and then use another way to spawn processes.

**Comment by mlenormand** [comment]
Got the solution : my npm.cmd has been deleted accidentally. Can be closed.

**Comment by rstoenescu** [comment]
I'm glad it's working! But please confirm it's nothing to do with the CLI.

**Comment by mlenormand** [comment]
Just modified my comment during you writed yours. It's not a bug, it's working now.
